language: node_js
node_js:
  - "0.10"
install:
  - "npm install"
  - "gem install rack"
  - "sudo apt-get install -qq python3-pip"
  - "sudo pip3 install Django"
before_script:
  - "ruby --version"
  - "python3 --version"
script:
  - "npm run-script test"
  - "npm run-script adapter-test"